### ISSUE TITLE
Unclear LICENSING

### ISSUE THREAD

**Issue by vuillaut** [codemeta/codemeta.github.io#36]
Hi
The `codemeta.json` file of this repository claims an MIT license:
https://github.com/codemeta/codemeta.github.io/blob/10df853b70bbc2f547c16e60e33a6913e5dd63cf/codemeta.json#L8

However, there is no general LICENSE file in the repository.
It would be great for potential contributors and developers to provide a clear LICENSE.

Thanks.

**Comment by cboettig** [comment]
Yeah, so this particular repository hosts the source for a website.  You'll note the website itself is actually labelled as cc-by.  Agree that a LICENSE file would probably be helpful all the same!

You link an example codemeta.json file that happens to be located in this repo, but as you can see in the rest of that file, that particular file is documenting an R package, not this website:
https://github.com/codemeta/codemeta.github.io/blob/10df853b70bbc2f547c16e60e33a6913e5dd63cf/codemeta.json#L1-L15
It's URL is not this repo, but another:
https://github.com/codemeta/codemeta.github.io/blob/10df853b70bbc2f547c16e60e33a6913e5dd63cf/codemeta.json#L278

It would be better for the `codemeta.json` example not to be placed in the repo root, as obviously this is confusing.  Still, according the JSON-LD and RDF standards, we shouldn't assume relationships are implicit  in the file structure / parent repo of a file, but should rather be explicitly stated.  HTH

**Comment by vuillaut** [comment]
> Yeah, so this particular repository hosts the source for a website. You'll note the website itself is actually labelled as cc-by. Agree that a LICENSE file would probably be helpful all the same!
> 
> You link an example codemeta.json file that happens to be located in this repo, but as you can see in the rest of that file, that particular file is documenting an R package, not this website:
> https://github.com/codemeta/codemeta.github.io/blob/10df853b70bbc2f547c16e60e33a6913e5dd63cf/codemeta.json#L1-L15
> 
> 
> It's URL is not this repo, but another:
> https://github.com/codemeta/codemeta.github.io/blob/10df853b70bbc2f547c16e60e33a6913e5dd63cf/codemeta.json#L278
> 
> It would be better for the `codemeta.json` example not to be placed in the repo root, as obviously this is confusing. Still, according the JSON-LD and RDF standards, we shouldn't assume relationships are implicit in the file structure / parent repo of a file, but should rather be explicitly stated. HTH

Thank you for the exhaustive and clear reply.
