### ISSUE TITLE
Implement automated procedure to deploy website with most recent vocabulary release

### ISSUE THREAD

**Issue by moranegg** [codemeta/codemeta.github.io#42]
Following up on this comment "an automated deployment model for the website, e.g. using GitHub Actions for blogdown sites, ideally using a single-branch setup for hosting both source and then the built static site in 'docs' rather than the current older convention of using a separate branch." from @cboettig on #32 

We will strive with the v3.0 release on codemeta/codemeta to have an automated process that will present the most recent release and crosswalks on website.

We have the resources to do so thanks to the FAIRCORE4EOSC project.

@cboettig, @mbjones, @progval and other PMC or community members: if you have any objection, please comment and raise concerns by May 10th.

**Comment by mbjones** [comment]
Sounds great to me.

**Comment by moranegg** [comment]
Thanks for the quick comment!
